set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang)

set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(ARCH_FLAGS "-target aarch64-linux-gnu")
set(CMAKE_C_FLAGS ${ARCH_FLAGS})
set(CMAKE_CXX_FLAGS ${ARCH_FLAGS})
set(CMAKE_ASM_FLAGS ${ARCH_FLAGS})
